local solution = require 'kyu7_SumOfIntegersInString'
describe("Fixed tests", function()
  it("", function()
    assert.are.same(solution.sumOfIntegersInString("12.4"),16)
    assert.are.same(solution.sumOfIntegersInString("h3ll0w0rld"),3)
    assert.are.same(solution.sumOfIntegersInString("2 + 3 = "),5)
    assert.are.same(solution.sumOfIntegersInString("Our company made approximately 1 million in gross revenue last quarter."),1)
    assert.are.same(solution.sumOfIntegersInString("The Great Depression lasted from 1929 to 1939."),3868)
    assert.are.same(solution.sumOfIntegersInString("Dogs are our best friends."),0)
    assert.are.same(solution.sumOfIntegersInString("C4t5 are 4m4z1ng."),18)
    assert.are.same(solution.sumOfIntegersInString("The30quick20brown10f0x1203jumps914ov3r1349the102l4zy dog"),3635)
 end)
end)
